sudo: false

language: bash

env:
  global:
    - PASS_VERSION=1.7.1 KCOV_VERSION=33

addons:
  apt:
    packages:
      - tree
      - xclip
      - shellcheck
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

matrix:
  include:
    - os: linux
      env:
        - PREFIX="$HOME/.bin/usr" PATH="$PATH:$PREFIX/bin"
      before_install:
        - wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.tar.gz
        - tar xzf v$KCOV_VERSION.tar.gz
        - mkdir kcov-$KCOV_VERSION/build
        - cd kcov-$KCOV_VERSION/build && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX .. && cd ../..
        - make --directory=kcov-$KCOV_VERSION/build
        - make install --directory=kcov-$KCOV_VERSION/build
        - rm -rf kcov-$KCOV_VERSION

    - os: osx
      env: PREFIX=/usr/local
      before_install:
        - brew install tree xclip shellcheck

install:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install

script:
  - make test

notifications:
  email: false
